const EErrors = {
  DEFAULT: 0,
  INCOMPLETE_VALUES: 1,
  INVALID_TYPES: 2,
  INVALID_VALUES: 3,
  INVALID_LENGTH: 4,
  MONGO_ERROR: 5,
  METHOD_NOT_IMPLEMENTED: 6,
  TEST_ERROR: 7,
}

export default EErrors
